### ISSUE TITLE
[bug] unsupported for osx 10.12

### ISSUE THREAD

**Issue by pow2n10** [shadowsocks/shadowsocks-go#156]
[bug] unsupported for osx 10.12

**Comment by iamtartan** [comment]
Client error on new MAC osx:
```
goroutine 88 [IO wait]:
net.runtime_pollWait(0x791c00, 0x72, 0xc820250400)
  /home/alex/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201d2300, 0x72, 0x0, 0x0)
  /home/alex/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201d2300, 0x0, 0x0)
  /home/alex/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201d22a0, 0xc820250400, 0x100c, 0x100c, 0x0, 0x6cd168, 0xc82000a1b0)
  /home/alex/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201d8038, 0xc820250400, 0x100c, 0x100c, 0x0, 0x0, 0x0)
  /home/alex/go/src/net/net.go:172 +0xe4
github.com/shadowsocks/shadowsocks-go/shadowsocks.(*Conn).Read(0xc8201daa50, 0xc820252800, 0x100c, 0x100c, 0x0, 0x0, 0x0)
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/conn.go:137 +0x287
github.com/shadowsocks/shadowsocks-go/shadowsocks.PipeThenClose(0x74e628, 0xc8201daa50, 0x70d180, 0xc820210038)
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/pipe.go:24 +0x13b
main.handleConnection(0x70d180, 0xc820210038)
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local/local.go:335 +0xa50
created by main.run
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local/local.go:363 +0x8f3

goroutine 56 [IO wait]:
net.runtime_pollWait(0x791d80, 0x72, 0xc820270000)
  /home/alex/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82025a060, 0x72, 0x0, 0x0)
  /home/alex/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82025a060, 0x0, 0x0)
  /home/alex/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82025a000, 0xc820270000, 0x100c, 0x100c, 0x0, 0x6cd168, 0xc82000a1b0)
  /home/alex/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820210038, 0xc820270000, 0x100c, 0x100c, 0x0, 0x0, 0x0)
  /home/alex/go/src/net/net.go:172 +0xe4
github.com/shadowsocks/shadowsocks-go/shadowsocks.PipeThenClose(0x70d180, 0xc820210038, 0x74e628, 0xc8201daa50)
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/pipe.go:24 +0x13b
created by main.handleConnection
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local/local.go:334 +0x9fd

goroutine 57 [IO wait]:
net.runtime_pollWait(0x791a80, 0x72, 0xc820271200)
  /home/alex/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82025a1b0, 0x72, 0x0, 0x0)
  /home/alex/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82025a1b0, 0x0, 0x0)
  /home/alex/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82025a150, 0xc820271200, 0x100c, 0x100c, 0x0, 0x6cd168, 0xc82000a1b0)
  /home/alex/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201d8050, 0xc820271200, 0x100c, 0x100c, 0x0, 0x0, 0x0)
  /home/alex/go/src/net/net.go:172 +0xe4
github.com/shadowsocks/shadowsocks-go/shadowsocks.(*Conn).Read(0xc8201dac80, 0xc820273600, 0x100c, 0x100c, 0x0, 0x0, 0x0)
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/conn.go:137 +0x287
github.com/shadowsocks/shadowsocks-go/shadowsocks.PipeThenClose(0x74e628, 0xc8201dac80, 0x70d180, 0xc8201d8040)
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/pipe.go:24 +0x13b
main.handleConnection(0x70d180, 0xc8201d8040)
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local/local.go:335 +0xa50
created by main.run
  /home/alex/gogo/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local/local.go:363 +0x8f3
```

**Comment by foisonocean** [comment]
I get a `permission denied` error in my macOS 10.12

**Comment by missdeer** [comment]
new version go compiler such as 1.7.4 is required for macOS 10.12 or higher
