### ISSUE TITLE
nil pointer dereference occurs while updating port/password

### ISSUE THREAD

**Issue by wmh** [shadowsocks/shadowsocks-go#262]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x52bb1f]

goroutine 1 [running]:
main.(*PasswdManager).updatePortPasswd(0x65f3d0, 0xc42008e8e0, 0x5, 0xc4200a2680, 0x20, 0x0)
        /go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:264 +0x1bf
main.updatePasswd()
        /go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:285 +0x252
main.waitSignal()
        /go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:303 +0x14e
main.main()
        /go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:454 +0x6b5`

**Comment by arthurkillerMB** [comment]
@arthurkiller 审核你MB帐户状态++你+arthurkillerMB+arthurkillerMB@arthurkiller 审核你MB帐户状态++你+arthurkillerMB+arthurkillerMB@arthurkiller 审核你MB帐户状态++你+arthurkillerMB+arthurkillerMB

**Comment by MBarthurkillerMB** [comment]
@arthurkiller 审核你MB帐户状态++你+arthurkillerMB+arthurkillerMB
