### ISSUE TITLE
数组切割错误runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by plbin97** [shadowsocks/shadowsocks-go#472]
2019/05/03 11:36:43 error getting request 112.66.98.115:28849 162.209.140.19:8202 addr type 9 not supported
2019/05/03 11:36:43 error getting request 223.104.4.48:6493 162.209.140.19:29102 read tcp 162.209.140.19:29102->223.104.4.48:6493: read: connection reset by peer
panic: runtime error: slice bounds out of range

goroutine 19839 [running]:
github.com/shadowsocks/shadowsocks-go/shadowsocks.handleUDPConnection(0xc004f47e00, 0x4, 0x5b7200, 0xc00b14f7a0, 0xc0063f0600, 0x100c, 0x100c, 0xc004f47e40)
	/home/olo/Work/Env/GoWork/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/udprelay.go:232 +0xdab
created by github.com/shadowsocks/shadowsocks-go/shadowsocks.ReadAndHandleUDPReq
	/home/olo/Work/Env/GoWork/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/udprelay.go:256 +0xf1

**Comment by plbin97** [comment]
我解决了这个问题
https://github.com/plbin97/shadowsocks-go
这里

**Comment by arthurkiller** [comment]
> 我解决了这个问题
> https://github.com/plbin97/shadowsocks-go
> 这里

you can put up a PR to fix this issue
